# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
    ]
