# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-10 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
